remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Title of your site
title: "All of Quantitative Finance"
description: "A summary of notes for quantitative finance."