# Run [bundle exec jekyll serve] to test the site locally

# page build set up
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  mathjax:
    process_escapes: true
  syntax_highlighter_opts:
    guess_lang: false

# site setting
title: "All of Quantitative Finance"
footer_content: "This website serves as a repository for all the materials shared and discussed during our seminar sessions. Contributions are provided by our dedicated seminar members:  
Deepesh Singhal,
<a href=\"https://github.com/QizhiZhao\">Qizhi Zhao</a>,
<a href=\"https://tianhaow.github.io\">Tianhao Wang</a>, 
<a href=\"https://github.com/Mathheadkang\">Xiaokang Wang</a>, 
<a href=\"https://github.com/zxmath\">Xu Zhuang</a>."


# This will always fix the navigation bar at the top
fixed_navbar: top
