remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    guess_lang: false

# Title of your site
title: "All of Quantitative Finance"
description: "This website serves as a repository for all the materials shared and discussed during our seminar sessions. Contributions are provided by our dedicated seminar members:  
Deepesh Singhal,
<a href=\"https://github.com/QizhiZhao\" style = \"color: white\">Qizhi Zhao</a>,
<a href=\"https://github.com/TianhaoW\" style = \"color: white\">Tianhao Wang</a>, 
<a href=\"https://github.com/Mathheadkang\" style = \"color: white\">Xiaokang Wang</a>, 
<a href=\"https://github.com/zxmath\" style = \"color: white\">Xu Zhuang</a>.
"

# Run [bundle exec jekyll serve] to test the site locally